New icons for HUL: e.g. questionnaires, versioning, file handling
UniversityofHelsinki/Styleguide pull request #132
Opened 2017-12-11 14:45 UTC by jpurma

Running 'gulp build' and 'gulp serve' in my machine created a css file with all -webkit-rules removed. To avoid this, the original css is used with icons manually put into their place.

2017-12-11 15:02 UTC, hheiskanen requested changes

2017-12-11 15:02 UTC, hheiskanen commented on css/styles.css
> +.icon--create-new-version:after {
Ikonien nimet kannattaa valita niin että ovat mahdollisimman geneerisiä. Myös sanamuoto kannattaa valita huolella siten että ikonien nimet ovat yhdenmukaisia, ts. kannattaa suosia lyhyitä nimiä ilman sovellusspesifiä semantiikkaa (jos versiointi-termiä haluaa välttämättä käyttää niin `new-version` on parempi nimi ilman turhaa edeltävää verbiä). Geneerisempi nimi tässä varmaan olisi `refresh` tai `update`.

2017-12-11 15:02 UTC, hheiskanen commented on css/styles.css
> +.icon--questionnaire-close:after {
Voisiko olla vain `close`? Ei saisi ottaa liikaa kantaa kontekstiin ja siihen mitä ollaan sulkemassa.

2017-12-11 15:02 UTC, hheiskanen commented on css/styles.css
> +.icon--questionnaire-open:after {
Tässä myös nimi liian spesifi. Voisi olla tässä tapauksessa vaikka `modify` tai `edit`

2017-12-11 15:02 UTC, hheiskanen commented on css/styles.css
> +.icon--file-numbers:after {
Parempi nimi olisi `chart`.

2017-12-11 15:02 UTC, hheiskanen commented on css/styles.css
> +.icon--template-part:after {
Nämä ikonit `template-part` ja `templates` ovat sen verran sovellus-spesifejä että en lisäisi niitä style guideen missä niille tuskin on muita käyttäjiä kuin HUL. Ne pitäisi ladata sovelluksen omista ikoneista.

2018-01-02 13:05 UTC, hheiskanen requested changes

2018-01-02 13:05 UTC, hheiskanen commented on css/styles.css
> +.icon--alert:after {
Toistuuko ikonien tyylit tässä nyt toistamiseen?

2018-01-02 13:05 UTC, hheiskanen commented on css/styles.css
> +.icon--file-chart:after {
pelkkä `chart` riittää nimeksi (kannattaa suosia lyhyitä nimiä bundle-kokojen minimoimiseksi ja ovat muutenkin nopeampia kirjoittaa)

2018-01-02 13:05 UTC, hheiskanen commented on css/styles.css
> +.icon--parts-all:after {
Jos nämä ottaa styleguideen mukaan niin ne pitäisi nimetä mahdollisimman geneerisesti. Voisi käyttää UniHow-spesifimmän `part`-termin sijaan vaikka geneerisimpää `item`-termiä -> nimiksi vaikka `items-list` ja `single-item`.

2018-01-02 13:05 UTC, hheiskanen commented on css/styles.css
> +.icon--questionnaire-close:after {
Tässäkin UniHow-spesifi `questionnaire`-termi. Voisiko niminä olla vain `close` ja `edit`?

2018-01-05 08:54 UTC, jpurma commented on css/styles.css
> +.icon--file-chart:after {
file-chart seuraa viereisen jo-olevan file-textin nimeämistä, molemmissa on samanlainen paperiarkki ympärillä kuvaamassa tiedostoa. Jos olisi pelkkä chart-ikoni, niin siinä ei olisi kehystä.

2018-01-05 08:57 UTC, jpurma commented on css/styles.css
> +.icon--questionnaire-close:after {
Tässäkin on close ja edit-symbolit kehysikonin sisällä, ja se kehysikoni on tuollainen tyypillinen kyselijän klipsutaulu. Ikonit kuvaavat tietynlaisen objektin sulkemista ja muokkaamista, jos olisi vain close ja edit, ei olisi ikonilla kehystä.

2018-01-05 08:59 UTC, jpurma commented on css/styles.css
> +.icon--parts-all:after {
Jos laitetaan items-set ja items-single. Tätä voi sitten uusiokäyttää kaikenlaisissa kokoelmissa.

2018-01-05 10:20 UTC, hheiskanen commented on css/styles.css
> +.icon--parts-all:after {
`item-set` on hyvä nimi. Toinen voi olla vaikka `item-single` niin ovat nimeämisen osalta linjassa keskenään.

2018-01-05 10:25 UTC, hheiskanen commented on css/styles.css
> +.icon--questionnaire-close:after {
En tiedä onko tarvetta huomioida tuota kehystä nimeämisessä mitenkään. Jos sen huomioi, niin silloin pitää käyttää `questionnaire`-termin sijaan jotain geneerisempää nimeä, esim: `form`, mutta se taas ei kuulosta muuten mielekkäältä. Käytännössähän sulkeminen implikoi aina jotain kohdetta, minkä takia minusta pelkkä `close` riittää hyvin nimeksi.

2018-01-05 10:29 UTC, hheiskanen commented on css/styles.css
> +.icon--questionnaire-close:after {
Toinen vaihtoehto voisi olla käyttää tuota `item`-termiä, kun vastaava kehys on käytössä myös noissa listaikoneissa. Tämän nimeksi voisi siten laittaa vaikka `item-close`.

2018-01-05 10:33 UTC, hheiskanen commented on css/styles.css
> +.icon--file-chart:after {
Niin tosiaan tuo `file-text` käyttää samanlaista kehystä. Siinä tapauksessa `file-chart` on tähän sopivin nimi.

2018-01-08 06:52 UTC, merged